author = "Yoshiharu Yamashita"
baseurl = "https://miteshdevelopment1.github.io/forestry/"
canonifyurls = true
copyright = "&copy; 2016. All rights reserved."
languageCode = "en-us"
paginate = 10
publishDir = "docs"
title = "Blackburn Theme Demo"
[indexes]
tag = "tags"
topic = "topics"
[[menu.main]]
name = "Contact"
pre = "<i class='fa fa-phone fa-fw'></i>"
url = "/contact/"
weight = 4
[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class='fa fa-user fa-fw'></i>"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "post"
name = "Posts"
pre = "<i class='fa fa-list fa-fw'></i>"
url = "/post/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fa fa-home fa-fw'></i>"
url = "/"
weight = 1
[params]
brand = "Blackburn"
dateformat = "2006-01-02T00:00:00+00:00"
disqus = "Your Disqus shortname"
googleanalytics = "Your Google Analytics tracking ID"
highlightjs = "androidstudio"
subtitle = "A Hugo Theme"
[social]
facebook = "*"
github = "yoshiharuyamashita"
instagram = "*"
linkedin = "*"
stackoverflow = "*"
twitter = "*"
